version: "3.7"
services:
  app:
    image: kooldev/php:8.0-nginx-prod
    restart: always
    #ports:
    #  - ${KOOL_APP_PORT:-80}:80
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
      PHP_DATE_TIMEZONE: ${PHP_TIMEZONE:-America/Sao_Paulo}
    volumes:
      - .:/app:delegated
      - $HOME/.ssh:/home/kool/.ssh:delegated
      - $HOME/.ssh:/root/.ssh:delegated
    networks:
      - kool_local
      - kool_global
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}-secured.rule=Host(`${PROJECT_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-secured.entrypoints=web-secured"
      - "traefik.http.services.${PROJECT_NAME}-secured.loadbalancer.server.port=80"
      #- "traefik.docker.network=${TRAEFIK_NETWORK:-traefik_proxy}"
  horizon:
    image: kooldev/php:8.0-prod
    restart: always
    command: bash -c "php /app/artisan horizon"
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
      NUM_PROCS: ${NUM_PROCS_WORKER:-1}
      PHP_DATE_TIMEZONE: ${PHP_TIMEZONE:-America/Sao_Paulo}
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  scheduler:
    image: kooldev/php:8.0-prod
    restart: always
    command: bash -c "php /app/artisan schedule:work"
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
      NUM_PROCS: ${NUM_PROCS_WORKER:-1}
      PHP_DATE_TIMEZONE: ${PHP_TIMEZONE:-America/Sao_Paulo}
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  database:
    image: mariadb:latest
    restart: always
    ports:
      - ${KOOL_DATABASE_PORT:-3306}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-rootpwd}
      MYSQL_DATABASE: ${DB_DATABASE-database}
      MYSQL_USER: ${DB_USERNAME-user}
      MYSQL_PASSWORD: ${DB_PASSWORD-userpwd}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - database:/var/lib/mysql:delegated
    networks:
      - kool_local
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
  cache:
    restart: always
    image: redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data:delegated
    networks:
      - kool_local
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
volumes:
  database: null
  cache: null
networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK:-traefik_proxy}
  kool_local: null
  kool_global:
    external: true
    name: ${KOOL_GLOBAL_NETWORK:-kool_global}
