on:
  push:
    branches: [ dev ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            kool run deploy
            sudo chown ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} ${{ secrets.SSH_PATH }} -R
            kool restart
#      - name: Notify workflow status
#        uses: yakuhzi/notify-telegram@v1
#        if: always()
#        with:
#          chat_id: ${{ secrets.CHAT_ID }}
#          bot_token: ${{ secrets.BOT_TOKEN }}
#          job_status: ${{ job.status }}
